# Generated by Django 6.0.1 on 2026-02-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('children/ya', 'Children/YA'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('mystery/thriller', 'Mystery/Thriller'), ('science fiction', 'Science Fiction'), ('historical fiction', 'Historical Fiction')], default='fiction', max_length=100),
        ),
    ]
