# Generated by Django 6.0.1 on 2026-02-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0002_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Children/YA', 'Children/YA'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Mystery/Thriller', 'Mystery/Thriller'), ('Science Fiction', 'Science Fiction'), ('Historical Fiction', 'Historical Fiction')], default='Fiction', max_length=100),
        ),
    ]
