# Generated by Django 6.0.1 on 2026-02-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0006_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('children', 'Children/YA'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery/Thriller'), ('scifi', 'Science Fiction'), ('historical', 'Historical Fiction')], default='Fiction', max_length=100),
        ),
    ]
