# Generated by Django 6.0.1 on 2026-02-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0008_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='genre',
        ),
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(default='country', max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstdjango.author'),
        ),
    ]
