# Generated by Django 6.0.1 on 2026-02-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0010_alter_book_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
